// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto
// Protobuf Java Version: 4.35.1

package io.grpc.health.v1;

@com.google.protobuf.Generated
public interface HealthListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.health.v1.HealthListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * statuses contains all the services and their respective status.
   * </pre>
   *
   * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
   */
  int getStatusesCount();
  /**
   * <pre>
   * statuses contains all the services and their respective status.
   * </pre>
   *
   * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
   */
  boolean containsStatuses(
      java.lang.String key);
  /**
   * Use {@link #getStatusesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse>
  getStatuses();
  /**
   * <pre>
   * statuses contains all the services and their respective status.
   * </pre>
   *
   * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
   */
  java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse>
  getStatusesMap();
  /**
   * <pre>
   * statuses contains all the services and their respective status.
   * </pre>
   *
   * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
   */
  /* nullable */
io.grpc.health.v1.HealthCheckResponse getStatusesOrDefault(
      java.lang.String key,
      /* nullable */
io.grpc.health.v1.HealthCheckResponse defaultValue);
  /**
   * <pre>
   * statuses contains all the services and their respective status.
   * </pre>
   *
   * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
   */
  io.grpc.health.v1.HealthCheckResponse getStatusesOrThrow(
      java.lang.String key);
}
