// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto
// Protobuf Java Version: 4.35.1

package io.grpc.health.v1;

@com.google.protobuf.Generated
public interface HealthListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.health.v1.HealthListRequest)
    com.google.protobuf.MessageOrBuilder {
}
