// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto
// Protobuf Java Version: 4.35.1

package io.grpc.health.v1;

@com.google.protobuf.Generated
public final class HealthProto extends com.google.protobuf.GeneratedFile {
  private HealthProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "HealthProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthCheckRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_health_v1_HealthCheckRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthCheckResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_health_v1_HealthCheckResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_health_v1_HealthListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_health_v1_HealthListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_health_v1_HealthListResponse_StatusesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_grpc_health_v1_HealthListResponse_StatusesEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033grpc/health/v1/health.proto\022\016grpc.heal" +
      "th.v1\"%\n\022HealthCheckRequest\022\017\n\007service\030\001" +
      " \001(\t\"\251\001\n\023HealthCheckResponse\022A\n\006status\030\001" +
      " \001(\01621.grpc.health.v1.HealthCheckRespons" +
      "e.ServingStatus\"O\n\rServingStatus\022\013\n\007UNKN" +
      "OWN\020\000\022\013\n\007SERVING\020\001\022\017\n\013NOT_SERVING\020\002\022\023\n\017S" +
      "ERVICE_UNKNOWN\020\003\"\023\n\021HealthListRequest\"\256\001" +
      "\n\022HealthListResponse\022B\n\010statuses\030\001 \003(\01320" +
      ".grpc.health.v1.HealthListResponse.Statu" +
      "sesEntry\032T\n\rStatusesEntry\022\013\n\003key\030\001 \001(\t\0222" +
      "\n\005value\030\002 \001(\0132#.grpc.health.v1.HealthChe" +
      "ckResponse:\0028\0012\375\001\n\006Health\022P\n\005Check\022\".grp" +
      "c.health.v1.HealthCheckRequest\032#.grpc.he" +
      "alth.v1.HealthCheckResponse\022M\n\004List\022!.gr" +
      "pc.health.v1.HealthListRequest\032\".grpc.he" +
      "alth.v1.HealthListResponse\022R\n\005Watch\022\".gr" +
      "pc.health.v1.HealthCheckRequest\032#.grpc.h" +
      "ealth.v1.HealthCheckResponse0\001Bp\n\021io.grp" +
      "c.health.v1B\013HealthProtoP\001Z,google.golan" +
      "g.org/grpc/health/grpc_health_v1\242\002\014GrpcH" +
      "ealthV1\252\002\016Grpc.Health.V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_health_v1_HealthCheckRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_grpc_health_v1_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthCheckRequest_descriptor,
        new java.lang.String[] { "Service", });
    internal_static_grpc_health_v1_HealthCheckResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_grpc_health_v1_HealthCheckResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthCheckResponse_descriptor,
        new java.lang.String[] { "Status", });
    internal_static_grpc_health_v1_HealthListRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_grpc_health_v1_HealthListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_grpc_health_v1_HealthListResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_grpc_health_v1_HealthListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthListResponse_descriptor,
        new java.lang.String[] { "Statuses", });
    internal_static_grpc_health_v1_HealthListResponse_StatusesEntry_descriptor =
      internal_static_grpc_health_v1_HealthListResponse_descriptor.getNestedType(0);
    internal_static_grpc_health_v1_HealthListResponse_StatusesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_grpc_health_v1_HealthListResponse_StatusesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
