// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: grpc/health/v1/health.proto
// Protobuf Java Version: 4.35.1

package io.grpc.health.v1;

/**
 * Protobuf type {@code grpc.health.v1.HealthListResponse}
 */
@com.google.protobuf.Generated
public final class HealthListResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:grpc.health.v1.HealthListResponse)
    HealthListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "HealthListResponse");
  }
  // Use HealthListResponse.newBuilder() to construct.
  private HealthListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private HealthListResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.health.v1.HealthProto.internal_static_grpc_health_v1_HealthListResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.grpc.health.v1.HealthProto.internal_static_grpc_health_v1_HealthListResponse_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 1:
        return internalGetStatuses();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.health.v1.HealthProto.internal_static_grpc_health_v1_HealthListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.health.v1.HealthListResponse.class, io.grpc.health.v1.HealthListResponse.Builder.class);
  }

  public static final int STATUSES_FIELD_NUMBER = 1;
  private static final class StatusesDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, io.grpc.health.v1.HealthCheckResponse> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, io.grpc.health.v1.HealthCheckResponse>newDefaultInstance(
                io.grpc.health.v1.HealthProto.internal_static_grpc_health_v1_HealthListResponse_StatusesEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.MESSAGE,
                io.grpc.health.v1.HealthCheckResponse.getDefaultInstance());
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, io.grpc.health.v1.HealthCheckResponse> statuses_;
  private com.google.protobuf.MapField<java.lang.String, io.grpc.health.v1.HealthCheckResponse>
  internalGetStatuses() {
    if (statuses_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          StatusesDefaultEntryHolder.defaultEntry);
    }
    return statuses_;
  }
  public int getStatusesCount() {
    return internalGetStatuses().getMap().size();
  }
  /**
   * <pre>
   * statuses contains all the services and their respective status.
   * </pre>
   *
   * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
   */
  @java.lang.Override
  public boolean containsStatuses(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetStatuses().getMap().containsKey(key);
  }
  /**
   * Use {@link #getStatusesMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse> getStatuses() {
    return getStatusesMap();
  }
  /**
   * <pre>
   * statuses contains all the services and their respective status.
   * </pre>
   *
   * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse> getStatusesMap() {
    return internalGetStatuses().getMap();
  }
  /**
   * <pre>
   * statuses contains all the services and their respective status.
   * </pre>
   *
   * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
   */
  @java.lang.Override
  public /* nullable */
io.grpc.health.v1.HealthCheckResponse getStatusesOrDefault(
      java.lang.String key,
      /* nullable */
io.grpc.health.v1.HealthCheckResponse defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse> map =
        internalGetStatuses().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * statuses contains all the services and their respective status.
   * </pre>
   *
   * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
   */
  @java.lang.Override
  public io.grpc.health.v1.HealthCheckResponse getStatusesOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse> map =
        internalGetStatuses().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetStatuses(),
        StatusesDefaultEntryHolder.defaultEntry,
        1);
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    for (java.util.Map.Entry<java.lang.String, io.grpc.health.v1.HealthCheckResponse> entry
         : internalGetStatuses().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, io.grpc.health.v1.HealthCheckResponse>
      statuses__ = StatusesDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, statuses__);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.health.v1.HealthListResponse)) {
      return super.equals(obj);
    }
    io.grpc.health.v1.HealthListResponse other = (io.grpc.health.v1.HealthListResponse) obj;

    if (!internalGetStatuses().equals(
        other.internalGetStatuses())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (!internalGetStatuses().getMap().isEmpty()) {
      hash = (37 * hash) + STATUSES_FIELD_NUMBER;
      hash = (53 * hash) + internalGetStatuses().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.health.v1.HealthListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.health.v1.HealthListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.health.v1.HealthListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.health.v1.HealthListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.health.v1.HealthListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.health.v1.HealthListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.health.v1.HealthListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.health.v1.HealthListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.grpc.health.v1.HealthListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.grpc.health.v1.HealthListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.health.v1.HealthListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.health.v1.HealthListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.health.v1.HealthListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code grpc.health.v1.HealthListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:grpc.health.v1.HealthListResponse)
      io.grpc.health.v1.HealthListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.health.v1.HealthProto.internal_static_grpc_health_v1_HealthListResponse_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetStatuses();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 1:
          return internalGetMutableStatuses();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.health.v1.HealthProto.internal_static_grpc_health_v1_HealthListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.health.v1.HealthListResponse.class, io.grpc.health.v1.HealthListResponse.Builder.class);
    }

    // Construct using io.grpc.health.v1.HealthListResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      internalGetMutableStatuses().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.health.v1.HealthProto.internal_static_grpc_health_v1_HealthListResponse_descriptor;
    }

    @java.lang.Override
    public io.grpc.health.v1.HealthListResponse getDefaultInstanceForType() {
      return io.grpc.health.v1.HealthListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.grpc.health.v1.HealthListResponse build() {
      io.grpc.health.v1.HealthListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.grpc.health.v1.HealthListResponse buildPartial() {
      io.grpc.health.v1.HealthListResponse result = new io.grpc.health.v1.HealthListResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.grpc.health.v1.HealthListResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.statuses_ = internalGetStatuses().build(StatusesDefaultEntryHolder.defaultEntry);
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.health.v1.HealthListResponse) {
        return mergeFrom((io.grpc.health.v1.HealthListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.health.v1.HealthListResponse other) {
      if (other == io.grpc.health.v1.HealthListResponse.getDefaultInstance()) return this;
      internalGetMutableStatuses().mergeFrom(
          other.internalGetStatuses());
      bitField0_ |= 0x00000001;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.MapEntry<java.lang.String, io.grpc.health.v1.HealthCheckResponse>
              statuses__ = input.readMessage(
                  StatusesDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableStatuses().ensureBuilderMap().put(
                  statuses__.getKey(), statuses__.getValue());
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private static final class StatusesConverter implements com.google.protobuf.MapFieldBuilder.Converter<java.lang.String, io.grpc.health.v1.HealthCheckResponseOrBuilder, io.grpc.health.v1.HealthCheckResponse> {
      @java.lang.Override
      public io.grpc.health.v1.HealthCheckResponse build(io.grpc.health.v1.HealthCheckResponseOrBuilder val) {
        if (val instanceof io.grpc.health.v1.HealthCheckResponse) { return (io.grpc.health.v1.HealthCheckResponse) val; }
        return ((io.grpc.health.v1.HealthCheckResponse.Builder) val).build();
      }

      @java.lang.Override
      public com.google.protobuf.MapEntry<java.lang.String, io.grpc.health.v1.HealthCheckResponse> defaultEntry() {
        return StatusesDefaultEntryHolder.defaultEntry;
      }
    };
    private static final StatusesConverter statusesConverter = new StatusesConverter();

    private com.google.protobuf.MapFieldBuilder<
        java.lang.String, io.grpc.health.v1.HealthCheckResponseOrBuilder, io.grpc.health.v1.HealthCheckResponse, io.grpc.health.v1.HealthCheckResponse.Builder> statuses_;
    private com.google.protobuf.MapFieldBuilder<java.lang.String, io.grpc.health.v1.HealthCheckResponseOrBuilder, io.grpc.health.v1.HealthCheckResponse, io.grpc.health.v1.HealthCheckResponse.Builder>
        internalGetStatuses() {
      if (statuses_ == null) {
        return new com.google.protobuf.MapFieldBuilder<>(statusesConverter);
      }
      return statuses_;
    }
    private com.google.protobuf.MapFieldBuilder<java.lang.String, io.grpc.health.v1.HealthCheckResponseOrBuilder, io.grpc.health.v1.HealthCheckResponse, io.grpc.health.v1.HealthCheckResponse.Builder>
        internalGetMutableStatuses() {
      if (statuses_ == null) {
        statuses_ = new com.google.protobuf.MapFieldBuilder<>(statusesConverter);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return statuses_;
    }
    public int getStatusesCount() {
      return internalGetStatuses().ensureBuilderMap().size();
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
     */
    @java.lang.Override
    public boolean containsStatuses(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStatuses().ensureBuilderMap().containsKey(key);
    }
    /**
     * Use {@link #getStatusesMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse> getStatuses() {
      return getStatusesMap();
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse> getStatusesMap() {
      return internalGetStatuses().getImmutableMap();
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
     */
    @java.lang.Override
    public /* nullable */
io.grpc.health.v1.HealthCheckResponse getStatusesOrDefault(
        java.lang.String key,
        /* nullable */
io.grpc.health.v1.HealthCheckResponse defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponseOrBuilder> map = internalGetMutableStatuses().ensureBuilderMap();
      return map.containsKey(key) ? statusesConverter.build(map.get(key)) : defaultValue;
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
     */
    @java.lang.Override
    public io.grpc.health.v1.HealthCheckResponse getStatusesOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponseOrBuilder> map = internalGetMutableStatuses().ensureBuilderMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return statusesConverter.build(map.get(key));
    }
    public Builder clearStatuses() {
      bitField0_ = (bitField0_ & ~0x00000001);
      internalGetMutableStatuses().clear();
      return this;
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
     */
    public Builder removeStatuses(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableStatuses().ensureBuilderMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse>
        getMutableStatuses() {
      bitField0_ |= 0x00000001;
      return internalGetMutableStatuses().ensureMessageMap();
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
     */
    public Builder putStatuses(
        java.lang.String key,
        io.grpc.health.v1.HealthCheckResponse value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableStatuses().ensureBuilderMap()
          .put(key, value);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
     */
    public Builder putAllStatuses(
        java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponse> values) {
      for (java.util.Map.Entry<java.lang.String, io.grpc.health.v1.HealthCheckResponse> e : values.entrySet()) {
        if (e.getKey() == null || e.getValue() == null) {
          throw new NullPointerException();
        }
      }
      internalGetMutableStatuses().ensureBuilderMap()
          .putAll(values);
      bitField0_ |= 0x00000001;
      return this;
    }
    /**
     * <pre>
     * statuses contains all the services and their respective status.
     * </pre>
     *
     * <code>map&lt;string, .grpc.health.v1.HealthCheckResponse&gt; statuses = 1;</code>
     */
    public io.grpc.health.v1.HealthCheckResponse.Builder putStatusesBuilderIfAbsent(
        java.lang.String key) {
      java.util.Map<java.lang.String, io.grpc.health.v1.HealthCheckResponseOrBuilder> builderMap = internalGetMutableStatuses().ensureBuilderMap();
      io.grpc.health.v1.HealthCheckResponseOrBuilder entry = builderMap.get(key);
      if (entry == null) {
        entry = io.grpc.health.v1.HealthCheckResponse.newBuilder();
        builderMap.put(key, entry);
      }
      if (entry instanceof io.grpc.health.v1.HealthCheckResponse) {
        entry = ((io.grpc.health.v1.HealthCheckResponse) entry).toBuilder();
        builderMap.put(key, entry);
      }
      return (io.grpc.health.v1.HealthCheckResponse.Builder) entry;
    }

    // @@protoc_insertion_point(builder_scope:grpc.health.v1.HealthListResponse)
  }

  // @@protoc_insertion_point(class_scope:grpc.health.v1.HealthListResponse)
  private static final io.grpc.health.v1.HealthListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.health.v1.HealthListResponse();
  }

  public static io.grpc.health.v1.HealthListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HealthListResponse>
      PARSER = new com.google.protobuf.AbstractParser<HealthListResponse>() {
    @java.lang.Override
    public HealthListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<HealthListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HealthListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.grpc.health.v1.HealthListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

