// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/any.proto
// Protobuf Java Version: 4.35.1

package com.google.protobuf;

@com.google.protobuf.Generated
public interface AnyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:google.protobuf.Any)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Identifies the type of the serialized Protobuf message with a URI reference
   * consisting of a prefix ending in a slash and the fully-qualified type name.
   *
   * Example: type.googleapis.com/google.protobuf.StringValue
   *
   * This string must contain at least one `/` character, and the content after
   * the last `/` must be the fully-qualified name of the type in canonical
   * form, without a leading dot. Do not write a scheme on these URI references
   * so that clients do not attempt to contact them.
   *
   * The prefix is arbitrary and Protobuf implementations are expected to
   * simply strip off everything up to and including the last `/` to identify
   * the type. `type.googleapis.com/` is a common default prefix that some
   * legacy implementations require. This prefix does not indicate the origin of
   * the type, and URIs containing it are not expected to respond to any
   * requests.
   *
   * All type URL strings must be legal URI references with the additional
   * restriction (for the text format) that the content of the reference
   * must consist only of alphanumeric characters, percent-encoded escapes, and
   * characters in the following set (not including the outer backticks):
   * `/-.~_!$&amp;()*+,;=`. Despite our allowing percent encodings, implementations
   * should not unescape them to prevent confusion with existing parsers. For
   * example, `type.googleapis.com%2FFoo` should be rejected.
   *
   * In the original design of `Any`, the possibility of launching a type
   * resolution service at these type URLs was considered but Protobuf never
   * implemented one and considers contacting these URLs to be problematic and
   * a potential security issue. Do not attempt to contact type URLs.
   * </pre>
   *
   * <code>string type_url = 1;</code>
   * @return The typeUrl.
   */
  java.lang.String getTypeUrl();
  /**
   * <pre>
   * Identifies the type of the serialized Protobuf message with a URI reference
   * consisting of a prefix ending in a slash and the fully-qualified type name.
   *
   * Example: type.googleapis.com/google.protobuf.StringValue
   *
   * This string must contain at least one `/` character, and the content after
   * the last `/` must be the fully-qualified name of the type in canonical
   * form, without a leading dot. Do not write a scheme on these URI references
   * so that clients do not attempt to contact them.
   *
   * The prefix is arbitrary and Protobuf implementations are expected to
   * simply strip off everything up to and including the last `/` to identify
   * the type. `type.googleapis.com/` is a common default prefix that some
   * legacy implementations require. This prefix does not indicate the origin of
   * the type, and URIs containing it are not expected to respond to any
   * requests.
   *
   * All type URL strings must be legal URI references with the additional
   * restriction (for the text format) that the content of the reference
   * must consist only of alphanumeric characters, percent-encoded escapes, and
   * characters in the following set (not including the outer backticks):
   * `/-.~_!$&amp;()*+,;=`. Despite our allowing percent encodings, implementations
   * should not unescape them to prevent confusion with existing parsers. For
   * example, `type.googleapis.com%2FFoo` should be rejected.
   *
   * In the original design of `Any`, the possibility of launching a type
   * resolution service at these type URLs was considered but Protobuf never
   * implemented one and considers contacting these URLs to be problematic and
   * a potential security issue. Do not attempt to contact type URLs.
   * </pre>
   *
   * <code>string type_url = 1;</code>
   * @return The bytes for typeUrl.
   */
  com.google.protobuf.ByteString
      getTypeUrlBytes();

  /**
   * <pre>
   * Holds a Protobuf serialization of the type described by type_url.
   * </pre>
   *
   * <code>bytes value = 2;</code>
   * @return The value.
   */
  com.google.protobuf.ByteString getValue();
}
