// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: google/protobuf/timestamp.proto
// Protobuf Java Version: 4.35.1

package com.google.protobuf;

@com.google.protobuf.Generated
public final class TimestampProto extends com.google.protobuf.GeneratedFile {
  private TimestampProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "TimestampProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_google_protobuf_Timestamp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_google_protobuf_Timestamp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037google/protobuf/timestamp.proto\022\017googl" +
      "e.protobuf\"+\n\tTimestamp\022\017\n\007seconds\030\001 \001(\003" +
      "\022\r\n\005nanos\030\002 \001(\005B\205\001\n\023com.google.protobufB" +
      "\016TimestampProtoP\001Z2google.golang.org/pro" +
      "tobuf/types/known/timestamppb\370\001\001\242\002\003GPB\252\002" +
      "\036Google.Protobuf.WellKnownTypesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_google_protobuf_Timestamp_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_google_protobuf_Timestamp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_google_protobuf_Timestamp_descriptor,
        new java.lang.String[] { "Seconds", "Nanos", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
