// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: vtproto/vtproto/ext.proto
// Protobuf Java Version: 4.35.1

package com.google.protobuf;

@com.google.protobuf.Generated
public final class VTProto extends com.google.protobuf.GeneratedFile {
  private VTProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "VTProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
    registry.add(com.google.protobuf.VTProto.mempool);
    registry.add(com.google.protobuf.VTProto.ignoreUnknownFields);
    registry.add(com.google.protobuf.VTProto.options);
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OptsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vtproto.Opts)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool unique = 1;</code>
     * @return Whether the unique field is set.
     */
    boolean hasUnique();
    /**
     * <code>optional bool unique = 1;</code>
     * @return The unique.
     */
    boolean getUnique();
  }
  /**
   * <pre>
   * These options should be used during schema definition,
   * applying them to some of the fields in protobuf
   * </pre>
   *
   * Protobuf type {@code vtproto.Opts}
   */
  public static final class Opts extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:vtproto.Opts)
      OptsOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "Opts");
    }
    // Use Opts.newBuilder() to construct.
    private Opts(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Opts() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.protobuf.VTProto.internal_static_vtproto_Opts_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.google.protobuf.VTProto.internal_static_vtproto_Opts_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.protobuf.VTProto.internal_static_vtproto_Opts_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.protobuf.VTProto.Opts.class, com.google.protobuf.VTProto.Opts.Builder.class);
    }

    private int bitField0_;
    public static final int UNIQUE_FIELD_NUMBER = 1;
    private boolean unique_ = false;
    /**
     * <code>optional bool unique = 1;</code>
     * @return Whether the unique field is set.
     */
    @java.lang.Override
    public boolean hasUnique() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bool unique = 1;</code>
     * @return The unique.
     */
    @java.lang.Override
    public boolean getUnique() {
      return unique_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeBool(1, unique_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, unique_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.google.protobuf.VTProto.Opts)) {
        return super.equals(obj);
      }
      com.google.protobuf.VTProto.Opts other = (com.google.protobuf.VTProto.Opts) obj;

      if (hasUnique() != other.hasUnique()) return false;
      if (hasUnique()) {
        if (getUnique()
            != other.getUnique()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUnique()) {
        hash = (37 * hash) + UNIQUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getUnique());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.google.protobuf.VTProto.Opts parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.VTProto.Opts parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.VTProto.Opts parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.VTProto.Opts parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.VTProto.Opts parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.google.protobuf.VTProto.Opts parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.google.protobuf.VTProto.Opts parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.VTProto.Opts parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.google.protobuf.VTProto.Opts parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.google.protobuf.VTProto.Opts parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.google.protobuf.VTProto.Opts parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.google.protobuf.VTProto.Opts parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.google.protobuf.VTProto.Opts prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * These options should be used during schema definition,
     * applying them to some of the fields in protobuf
     * </pre>
     *
     * Protobuf type {@code vtproto.Opts}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vtproto.Opts)
        com.google.protobuf.VTProto.OptsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.google.protobuf.VTProto.internal_static_vtproto_Opts_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.google.protobuf.VTProto.internal_static_vtproto_Opts_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.google.protobuf.VTProto.Opts.class, com.google.protobuf.VTProto.Opts.Builder.class);
      }

      // Construct using com.google.protobuf.VTProto.Opts.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        unique_ = false;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.google.protobuf.VTProto.internal_static_vtproto_Opts_descriptor;
      }

      @java.lang.Override
      public com.google.protobuf.VTProto.Opts getDefaultInstanceForType() {
        return com.google.protobuf.VTProto.Opts.getDefaultInstance();
      }

      @java.lang.Override
      public com.google.protobuf.VTProto.Opts build() {
        com.google.protobuf.VTProto.Opts result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.google.protobuf.VTProto.Opts buildPartial() {
        com.google.protobuf.VTProto.Opts result = new com.google.protobuf.VTProto.Opts(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.google.protobuf.VTProto.Opts result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.unique_ = unique_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.google.protobuf.VTProto.Opts) {
          return mergeFrom((com.google.protobuf.VTProto.Opts)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.google.protobuf.VTProto.Opts other) {
        if (other == com.google.protobuf.VTProto.Opts.getDefaultInstance()) return this;
        if (other.hasUnique()) {
          setUnique(other.getUnique());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                unique_ = input.readBool();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private boolean unique_ ;
      /**
       * <code>optional bool unique = 1;</code>
       * @return Whether the unique field is set.
       */
      @java.lang.Override
      public boolean hasUnique() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional bool unique = 1;</code>
       * @return The unique.
       */
      @java.lang.Override
      public boolean getUnique() {
        return unique_;
      }
      /**
       * <code>optional bool unique = 1;</code>
       * @param value The unique to set.
       * @return This builder for chaining.
       */
      public Builder setUnique(boolean value) {

        unique_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool unique = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUnique() {
        bitField0_ = (bitField0_ & ~0x00000001);
        unique_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:vtproto.Opts)
    }

    // @@protoc_insertion_point(class_scope:vtproto.Opts)
    private static final com.google.protobuf.VTProto.Opts DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.google.protobuf.VTProto.Opts();
    }

    public static com.google.protobuf.VTProto.Opts getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Opts>
        PARSER = new com.google.protobuf.AbstractParser<Opts>() {
      @java.lang.Override
      public Opts parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Opts> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Opts> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.VTProto.Opts getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int MEMPOOL_FIELD_NUMBER = 64101;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> mempool = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int IGNORE_UNKNOWN_FIELDS_FIELD_NUMBER = 64102;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      java.lang.Boolean> ignoreUnknownFields = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        java.lang.Boolean.class,
        null);
  public static final int OPTIONS_FIELD_NUMBER = 64150;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      com.google.protobuf.VTProto.Opts> options = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        com.google.protobuf.VTProto.Opts.class,
        com.google.protobuf.VTProto.Opts.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vtproto_Opts_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_vtproto_Opts_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031vtproto/vtproto/ext.proto\022\007vtproto\032 go" +
      "ogle/protobuf/descriptor.proto\"\026\n\004Opts\022\016" +
      "\n\006unique\030\001 \001(\010:2\n\007mempool\022\037.google.proto" +
      "buf.MessageOptions\030\345\364\003 \001(\010:@\n\025ignore_unk" +
      "nown_fields\022\037.google.protobuf.MessageOpt" +
      "ions\030\346\364\003 \001(\010:?\n\007options\022\035.google.protobu" +
      "f.FieldOptions\030\226\365\003 \001(\0132\r.vtproto.OptsBI\n" +
      "\023com.google.protobufB\007VTProtoZ)github.co" +
      "m/planetscale/vtprotobuf/vtproto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        });
    internal_static_vtproto_Opts_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_vtproto_Opts_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_vtproto_Opts_descriptor,
        new java.lang.String[] { "Unique", });
    mempool.internalInit(descriptor.getExtension(0));
    ignoreUnknownFields.internalInit(descriptor.getExtension(1));
    options.internalInit(descriptor.getExtension(2));
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
