// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fsutil/types/stat.proto
// Protobuf Java Version: 4.35.1

package fsutil.types;

@com.google.protobuf.Generated
public final class StatOuterClass extends com.google.protobuf.GeneratedFile {
  private StatOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "StatOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fsutil.types.Stat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    java.lang.String getPath();
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    com.google.protobuf.ByteString
        getPathBytes();

    /**
     * <code>uint32 mode = 2;</code>
     * @return The mode.
     */
    int getMode();

    /**
     * <code>uint32 uid = 3;</code>
     * @return The uid.
     */
    int getUid();

    /**
     * <code>uint32 gid = 4;</code>
     * @return The gid.
     */
    int getGid();

    /**
     * <code>int64 size = 5;</code>
     * @return The size.
     */
    long getSize();

    /**
     * <code>int64 modTime = 6;</code>
     * @return The modTime.
     */
    long getModTime();

    /**
     * <pre>
     * int32 typeflag = 7;
     * </pre>
     *
     * <code>string linkname = 7;</code>
     * @return The linkname.
     */
    java.lang.String getLinkname();
    /**
     * <pre>
     * int32 typeflag = 7;
     * </pre>
     *
     * <code>string linkname = 7;</code>
     * @return The bytes for linkname.
     */
    com.google.protobuf.ByteString
        getLinknameBytes();

    /**
     * <code>int64 devmajor = 8;</code>
     * @return The devmajor.
     */
    long getDevmajor();

    /**
     * <code>int64 devminor = 9;</code>
     * @return The devminor.
     */
    long getDevminor();

    /**
     * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
     */
    int getXattrsCount();
    /**
     * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
     */
    boolean containsXattrs(
        java.lang.String key);
    /**
     * Use {@link #getXattrsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getXattrs();
    /**
     * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
     */
    java.util.Map<java.lang.String, com.google.protobuf.ByteString>
    getXattrsMap();
    /**
     * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
     */
    /* nullable */
com.google.protobuf.ByteString getXattrsOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.ByteString defaultValue);
    /**
     * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
     */
    com.google.protobuf.ByteString getXattrsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code fsutil.types.Stat}
   */
  public static final class Stat extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:fsutil.types.Stat)
      StatOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "Stat");
    }
    // Use Stat.newBuilder() to construct.
    private Stat(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Stat() {
      path_ = "";
      linkname_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fsutil.types.StatOuterClass.internal_static_fsutil_types_Stat_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return fsutil.types.StatOuterClass.internal_static_fsutil_types_Stat_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 10:
          return internalGetXattrs();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fsutil.types.StatOuterClass.internal_static_fsutil_types_Stat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fsutil.types.StatOuterClass.Stat.class, fsutil.types.StatOuterClass.Stat.Builder.class);
    }

    public static final int PATH_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object path_ = "";
    /**
     * <code>string path = 1;</code>
     * @return The path.
     */
    @java.lang.Override
    public java.lang.String getPath() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        path_ = s;
        return s;
      }
    }
    /**
     * <code>string path = 1;</code>
     * @return The bytes for path.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPathBytes() {
      java.lang.Object ref = path_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        path_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODE_FIELD_NUMBER = 2;
    private int mode_ = 0;
    /**
     * <code>uint32 mode = 2;</code>
     * @return The mode.
     */
    @java.lang.Override
    public int getMode() {
      return mode_;
    }

    public static final int UID_FIELD_NUMBER = 3;
    private int uid_ = 0;
    /**
     * <code>uint32 uid = 3;</code>
     * @return The uid.
     */
    @java.lang.Override
    public int getUid() {
      return uid_;
    }

    public static final int GID_FIELD_NUMBER = 4;
    private int gid_ = 0;
    /**
     * <code>uint32 gid = 4;</code>
     * @return The gid.
     */
    @java.lang.Override
    public int getGid() {
      return gid_;
    }

    public static final int SIZE_FIELD_NUMBER = 5;
    private long size_ = 0L;
    /**
     * <code>int64 size = 5;</code>
     * @return The size.
     */
    @java.lang.Override
    public long getSize() {
      return size_;
    }

    public static final int MODTIME_FIELD_NUMBER = 6;
    private long modTime_ = 0L;
    /**
     * <code>int64 modTime = 6;</code>
     * @return The modTime.
     */
    @java.lang.Override
    public long getModTime() {
      return modTime_;
    }

    public static final int LINKNAME_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object linkname_ = "";
    /**
     * <pre>
     * int32 typeflag = 7;
     * </pre>
     *
     * <code>string linkname = 7;</code>
     * @return The linkname.
     */
    @java.lang.Override
    public java.lang.String getLinkname() {
      java.lang.Object ref = linkname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        linkname_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * int32 typeflag = 7;
     * </pre>
     *
     * <code>string linkname = 7;</code>
     * @return The bytes for linkname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLinknameBytes() {
      java.lang.Object ref = linkname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        linkname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVMAJOR_FIELD_NUMBER = 8;
    private long devmajor_ = 0L;
    /**
     * <code>int64 devmajor = 8;</code>
     * @return The devmajor.
     */
    @java.lang.Override
    public long getDevmajor() {
      return devmajor_;
    }

    public static final int DEVMINOR_FIELD_NUMBER = 9;
    private long devminor_ = 0L;
    /**
     * <code>int64 devminor = 9;</code>
     * @return The devminor.
     */
    @java.lang.Override
    public long getDevminor() {
      return devminor_;
    }

    public static final int XATTRS_FIELD_NUMBER = 10;
    private static final class XattrsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.google.protobuf.ByteString> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                  fsutil.types.StatOuterClass.internal_static_fsutil_types_Stat_XattrsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.BYTES,
                  com.google.protobuf.ByteString.EMPTY);
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> xattrs_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
    internalGetXattrs() {
      if (xattrs_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            XattrsDefaultEntryHolder.defaultEntry);
      }
      return xattrs_;
    }
    public int getXattrsCount() {
      return internalGetXattrs().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
     */
    @java.lang.Override
    public boolean containsXattrs(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetXattrs().getMap().containsKey(key);
    }
    /**
     * Use {@link #getXattrsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getXattrs() {
      return getXattrsMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getXattrsMap() {
      return internalGetXattrs().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.ByteString getXattrsOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetXattrs().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getXattrsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetXattrs().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(path_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, path_);
      }
      if (mode_ != 0) {
        output.writeUInt32(2, mode_);
      }
      if (uid_ != 0) {
        output.writeUInt32(3, uid_);
      }
      if (gid_ != 0) {
        output.writeUInt32(4, gid_);
      }
      if (size_ != 0L) {
        output.writeInt64(5, size_);
      }
      if (modTime_ != 0L) {
        output.writeInt64(6, modTime_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(linkname_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, linkname_);
      }
      if (devmajor_ != 0L) {
        output.writeInt64(8, devmajor_);
      }
      if (devminor_ != 0L) {
        output.writeInt64(9, devminor_);
      }
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetXattrs(),
          XattrsDefaultEntryHolder.defaultEntry,
          10);
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(path_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, path_);
      }
      if (mode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, mode_);
      }
      if (uid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, uid_);
      }
      if (gid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, gid_);
      }
      if (size_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, size_);
      }
      if (modTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, modTime_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(linkname_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(7, linkname_);
      }
      if (devmajor_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(8, devmajor_);
      }
      if (devminor_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, devminor_);
      }
      for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
           : internalGetXattrs().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
        xattrs__ = XattrsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .buildPartial();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(10, xattrs__);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fsutil.types.StatOuterClass.Stat)) {
        return super.equals(obj);
      }
      fsutil.types.StatOuterClass.Stat other = (fsutil.types.StatOuterClass.Stat) obj;

      if (!getPath()
          .equals(other.getPath())) return false;
      if (getMode()
          != other.getMode()) return false;
      if (getUid()
          != other.getUid()) return false;
      if (getGid()
          != other.getGid()) return false;
      if (getSize()
          != other.getSize()) return false;
      if (getModTime()
          != other.getModTime()) return false;
      if (!getLinkname()
          .equals(other.getLinkname())) return false;
      if (getDevmajor()
          != other.getDevmajor()) return false;
      if (getDevminor()
          != other.getDevminor()) return false;
      if (!internalGetXattrs().equals(
          other.internalGetXattrs())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATH_FIELD_NUMBER;
      hash = (53 * hash) + getPath().hashCode();
      hash = (37 * hash) + MODE_FIELD_NUMBER;
      hash = (53 * hash) + getMode();
      hash = (37 * hash) + UID_FIELD_NUMBER;
      hash = (53 * hash) + getUid();
      hash = (37 * hash) + GID_FIELD_NUMBER;
      hash = (53 * hash) + getGid();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSize());
      hash = (37 * hash) + MODTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getModTime());
      hash = (37 * hash) + LINKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getLinkname().hashCode();
      hash = (37 * hash) + DEVMAJOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDevmajor());
      hash = (37 * hash) + DEVMINOR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDevminor());
      if (!internalGetXattrs().getMap().isEmpty()) {
        hash = (37 * hash) + XATTRS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetXattrs().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fsutil.types.StatOuterClass.Stat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsutil.types.StatOuterClass.Stat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsutil.types.StatOuterClass.Stat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsutil.types.StatOuterClass.Stat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsutil.types.StatOuterClass.Stat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsutil.types.StatOuterClass.Stat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsutil.types.StatOuterClass.Stat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fsutil.types.StatOuterClass.Stat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fsutil.types.StatOuterClass.Stat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fsutil.types.StatOuterClass.Stat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsutil.types.StatOuterClass.Stat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fsutil.types.StatOuterClass.Stat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fsutil.types.StatOuterClass.Stat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fsutil.types.Stat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fsutil.types.Stat)
        fsutil.types.StatOuterClass.StatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fsutil.types.StatOuterClass.internal_static_fsutil_types_Stat_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 10:
            return internalGetXattrs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 10:
            return internalGetMutableXattrs();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fsutil.types.StatOuterClass.internal_static_fsutil_types_Stat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fsutil.types.StatOuterClass.Stat.class, fsutil.types.StatOuterClass.Stat.Builder.class);
      }

      // Construct using fsutil.types.StatOuterClass.Stat.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        path_ = "";
        mode_ = 0;
        uid_ = 0;
        gid_ = 0;
        size_ = 0L;
        modTime_ = 0L;
        linkname_ = "";
        devmajor_ = 0L;
        devminor_ = 0L;
        internalGetMutableXattrs().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fsutil.types.StatOuterClass.internal_static_fsutil_types_Stat_descriptor;
      }

      @java.lang.Override
      public fsutil.types.StatOuterClass.Stat getDefaultInstanceForType() {
        return fsutil.types.StatOuterClass.Stat.getDefaultInstance();
      }

      @java.lang.Override
      public fsutil.types.StatOuterClass.Stat build() {
        fsutil.types.StatOuterClass.Stat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fsutil.types.StatOuterClass.Stat buildPartial() {
        fsutil.types.StatOuterClass.Stat result = new fsutil.types.StatOuterClass.Stat(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(fsutil.types.StatOuterClass.Stat result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.path_ = path_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.mode_ = mode_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.uid_ = uid_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.gid_ = gid_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.size_ = size_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.modTime_ = modTime_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.linkname_ = linkname_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.devmajor_ = devmajor_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.devminor_ = devminor_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.xattrs_ = internalGetXattrs();
          result.xattrs_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fsutil.types.StatOuterClass.Stat) {
          return mergeFrom((fsutil.types.StatOuterClass.Stat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fsutil.types.StatOuterClass.Stat other) {
        if (other == fsutil.types.StatOuterClass.Stat.getDefaultInstance()) return this;
        if (!other.getPath().isEmpty()) {
          path_ = other.path_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getMode() != 0) {
          setMode(other.getMode());
        }
        if (other.getUid() != 0) {
          setUid(other.getUid());
        }
        if (other.getGid() != 0) {
          setGid(other.getGid());
        }
        if (other.getSize() != 0L) {
          setSize(other.getSize());
        }
        if (other.getModTime() != 0L) {
          setModTime(other.getModTime());
        }
        if (!other.getLinkname().isEmpty()) {
          linkname_ = other.linkname_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getDevmajor() != 0L) {
          setDevmajor(other.getDevmajor());
        }
        if (other.getDevminor() != 0L) {
          setDevminor(other.getDevminor());
        }
        internalGetMutableXattrs().mergeFrom(
            other.internalGetXattrs());
        bitField0_ |= 0x00000200;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                path_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                mode_ = input.readUInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                uid_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                gid_ = input.readUInt32();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 40: {
                size_ = input.readInt64();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                modTime_ = input.readInt64();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 58: {
                linkname_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                devmajor_ = input.readInt64();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 72: {
                devminor_ = input.readInt64();
                bitField0_ |= 0x00000100;
                break;
              } // case 72
              case 82: {
                com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
                xattrs__ = input.readMessage(
                    XattrsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableXattrs().getMutableMap().put(
                    xattrs__.getKey(), xattrs__.getValue());
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object path_ = "";
      /**
       * <code>string path = 1;</code>
       * @return The path.
       */
      public java.lang.String getPath() {
        java.lang.Object ref = path_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          path_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string path = 1;</code>
       * @return The bytes for path.
       */
      public com.google.protobuf.ByteString
          getPathBytes() {
        java.lang.Object ref = path_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          path_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string path = 1;</code>
       * @param value The path to set.
       * @return This builder for chaining.
       */
      public Builder setPath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        path_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPath() {
        path_ = getDefaultInstance().getPath();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string path = 1;</code>
       * @param value The bytes for path to set.
       * @return This builder for chaining.
       */
      public Builder setPathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        path_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int mode_ ;
      /**
       * <code>uint32 mode = 2;</code>
       * @return The mode.
       */
      @java.lang.Override
      public int getMode() {
        return mode_;
      }
      /**
       * <code>uint32 mode = 2;</code>
       * @param value The mode to set.
       * @return This builder for chaining.
       */
      public Builder setMode(int value) {

        mode_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 mode = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mode_ = 0;
        onChanged();
        return this;
      }

      private int uid_ ;
      /**
       * <code>uint32 uid = 3;</code>
       * @return The uid.
       */
      @java.lang.Override
      public int getUid() {
        return uid_;
      }
      /**
       * <code>uint32 uid = 3;</code>
       * @param value The uid to set.
       * @return This builder for chaining.
       */
      public Builder setUid(int value) {

        uid_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 uid = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUid() {
        bitField0_ = (bitField0_ & ~0x00000004);
        uid_ = 0;
        onChanged();
        return this;
      }

      private int gid_ ;
      /**
       * <code>uint32 gid = 4;</code>
       * @return The gid.
       */
      @java.lang.Override
      public int getGid() {
        return gid_;
      }
      /**
       * <code>uint32 gid = 4;</code>
       * @param value The gid to set.
       * @return This builder for chaining.
       */
      public Builder setGid(int value) {

        gid_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 gid = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        gid_ = 0;
        onChanged();
        return this;
      }

      private long size_ ;
      /**
       * <code>int64 size = 5;</code>
       * @return The size.
       */
      @java.lang.Override
      public long getSize() {
        return size_;
      }
      /**
       * <code>int64 size = 5;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(long value) {

        size_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int64 size = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        size_ = 0L;
        onChanged();
        return this;
      }

      private long modTime_ ;
      /**
       * <code>int64 modTime = 6;</code>
       * @return The modTime.
       */
      @java.lang.Override
      public long getModTime() {
        return modTime_;
      }
      /**
       * <code>int64 modTime = 6;</code>
       * @param value The modTime to set.
       * @return This builder for chaining.
       */
      public Builder setModTime(long value) {

        modTime_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int64 modTime = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearModTime() {
        bitField0_ = (bitField0_ & ~0x00000020);
        modTime_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object linkname_ = "";
      /**
       * <pre>
       * int32 typeflag = 7;
       * </pre>
       *
       * <code>string linkname = 7;</code>
       * @return The linkname.
       */
      public java.lang.String getLinkname() {
        java.lang.Object ref = linkname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          linkname_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * int32 typeflag = 7;
       * </pre>
       *
       * <code>string linkname = 7;</code>
       * @return The bytes for linkname.
       */
      public com.google.protobuf.ByteString
          getLinknameBytes() {
        java.lang.Object ref = linkname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          linkname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * int32 typeflag = 7;
       * </pre>
       *
       * <code>string linkname = 7;</code>
       * @param value The linkname to set.
       * @return This builder for chaining.
       */
      public Builder setLinkname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        linkname_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * int32 typeflag = 7;
       * </pre>
       *
       * <code>string linkname = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearLinkname() {
        linkname_ = getDefaultInstance().getLinkname();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * int32 typeflag = 7;
       * </pre>
       *
       * <code>string linkname = 7;</code>
       * @param value The bytes for linkname to set.
       * @return This builder for chaining.
       */
      public Builder setLinknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        linkname_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private long devmajor_ ;
      /**
       * <code>int64 devmajor = 8;</code>
       * @return The devmajor.
       */
      @java.lang.Override
      public long getDevmajor() {
        return devmajor_;
      }
      /**
       * <code>int64 devmajor = 8;</code>
       * @param value The devmajor to set.
       * @return This builder for chaining.
       */
      public Builder setDevmajor(long value) {

        devmajor_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int64 devmajor = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearDevmajor() {
        bitField0_ = (bitField0_ & ~0x00000080);
        devmajor_ = 0L;
        onChanged();
        return this;
      }

      private long devminor_ ;
      /**
       * <code>int64 devminor = 9;</code>
       * @return The devminor.
       */
      @java.lang.Override
      public long getDevminor() {
        return devminor_;
      }
      /**
       * <code>int64 devminor = 9;</code>
       * @param value The devminor to set.
       * @return This builder for chaining.
       */
      public Builder setDevminor(long value) {

        devminor_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>int64 devminor = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearDevminor() {
        bitField0_ = (bitField0_ & ~0x00000100);
        devminor_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.google.protobuf.ByteString> xattrs_;
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
          internalGetXattrs() {
        if (xattrs_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              XattrsDefaultEntryHolder.defaultEntry);
        }
        return xattrs_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
          internalGetMutableXattrs() {
        if (xattrs_ == null) {
          xattrs_ = com.google.protobuf.MapField.newMapField(
              XattrsDefaultEntryHolder.defaultEntry);
        }
        if (!xattrs_.isMutable()) {
          xattrs_ = xattrs_.copy();
        }
        bitField0_ |= 0x00000200;
        onChanged();
        return xattrs_;
      }
      public int getXattrsCount() {
        return internalGetXattrs().getMap().size();
      }
      /**
       * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
       */
      @java.lang.Override
      public boolean containsXattrs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetXattrs().getMap().containsKey(key);
      }
      /**
       * Use {@link #getXattrsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getXattrs() {
        return getXattrsMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getXattrsMap() {
        return internalGetXattrs().getMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
       */
      @java.lang.Override
      public /* nullable */
com.google.protobuf.ByteString getXattrsOrDefault(
          java.lang.String key,
          /* nullable */
com.google.protobuf.ByteString defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetXattrs().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getXattrsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
            internalGetXattrs().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearXattrs() {
        bitField0_ = (bitField0_ & ~0x00000200);
        internalGetMutableXattrs().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
       */
      public Builder removeXattrs(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableXattrs().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
          getMutableXattrs() {
        bitField0_ |= 0x00000200;
        return internalGetMutableXattrs().getMutableMap();
      }
      /**
       * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
       */
      public Builder putXattrs(
          java.lang.String key,
          com.google.protobuf.ByteString value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableXattrs().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000200;
        return this;
      }
      /**
       * <code>map&lt;string, bytes&gt; xattrs = 10;</code>
       */
      public Builder putAllXattrs(
          java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
        internalGetMutableXattrs().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000200;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fsutil.types.Stat)
    }

    // @@protoc_insertion_point(class_scope:fsutil.types.Stat)
    private static final fsutil.types.StatOuterClass.Stat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fsutil.types.StatOuterClass.Stat();
    }

    public static fsutil.types.StatOuterClass.Stat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Stat>
        PARSER = new com.google.protobuf.AbstractParser<Stat>() {
      @java.lang.Override
      public Stat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Stat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Stat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fsutil.types.StatOuterClass.Stat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fsutil_types_Stat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fsutil_types_Stat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fsutil_types_Stat_XattrsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fsutil_types_Stat_XattrsEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027fsutil/types/stat.proto\022\014fsutil.types\032" +
      "\031vtproto/vtproto/ext.proto\"\360\001\n\004Stat\022\014\n\004p" +
      "ath\030\001 \001(\t\022\014\n\004mode\030\002 \001(\r\022\013\n\003uid\030\003 \001(\r\022\013\n\003" +
      "gid\030\004 \001(\r\022\014\n\004size\030\005 \001(\003\022\017\n\007modTime\030\006 \001(\003" +
      "\022\020\n\010linkname\030\007 \001(\t\022\020\n\010devmajor\030\010 \001(\003\022\020\n\010" +
      "devminor\030\t \001(\003\022.\n\006xattrs\030\n \003(\0132\036.fsutil." +
      "types.Stat.XattrsEntry\032-\n\013XattrsEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\014:\0028\001B$Z\"github." +
      "com/tonistiigi/fsutil/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.VTProto.getDescriptor(),
        });
    internal_static_fsutil_types_Stat_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_fsutil_types_Stat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fsutil_types_Stat_descriptor,
        new java.lang.String[] { "Path", "Mode", "Uid", "Gid", "Size", "ModTime", "Linkname", "Devmajor", "Devminor", "Xattrs", });
    internal_static_fsutil_types_Stat_XattrsEntry_descriptor =
      internal_static_fsutil_types_Stat_descriptor.getNestedType(0);
    internal_static_fsutil_types_Stat_XattrsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fsutil_types_Stat_XattrsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.VTProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
