// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fsutil/types/wire.proto
// Protobuf Java Version: 4.35.1

package fsutil.types;

@com.google.protobuf.Generated
public final class Wire extends com.google.protobuf.GeneratedFile {
  private Wire() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Wire");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:fsutil.types.Packet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.fsutil.types.Packet.PacketType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.fsutil.types.Packet.PacketType type = 1;</code>
     * @return The type.
     */
    fsutil.types.Wire.Packet.PacketType getType();

    /**
     * <code>.fsutil.types.Stat stat = 2;</code>
     * @return Whether the stat field is set.
     */
    boolean hasStat();
    /**
     * <code>.fsutil.types.Stat stat = 2;</code>
     * @return The stat.
     */
    fsutil.types.StatOuterClass.Stat getStat();
    /**
     * <code>.fsutil.types.Stat stat = 2;</code>
     */
    fsutil.types.StatOuterClass.StatOrBuilder getStatOrBuilder();

    /**
     * <code>uint32 ID = 3;</code>
     * @return The iD.
     */
    int getID();

    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code fsutil.types.Packet}
   */
  public static final class Packet extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:fsutil.types.Packet)
      PacketOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "Packet");
    }
    // Use Packet.newBuilder() to construct.
    private Packet(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Packet() {
      type_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fsutil.types.Wire.internal_static_fsutil_types_Packet_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return fsutil.types.Wire.internal_static_fsutil_types_Packet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fsutil.types.Wire.internal_static_fsutil_types_Packet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fsutil.types.Wire.Packet.class, fsutil.types.Wire.Packet.Builder.class);
    }

    /**
     * Protobuf enum {@code fsutil.types.Packet.PacketType}
     */
    public enum PacketType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PACKET_STAT = 0;</code>
       */
      PACKET_STAT(0),
      /**
       * <code>PACKET_REQ = 1;</code>
       */
      PACKET_REQ(1),
      /**
       * <code>PACKET_DATA = 2;</code>
       */
      PACKET_DATA(2),
      /**
       * <code>PACKET_FIN = 3;</code>
       */
      PACKET_FIN(3),
      /**
       * <code>PACKET_ERR = 4;</code>
       */
      PACKET_ERR(4),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 35,
          /* patch= */ 1,
          /* suffix= */ "",
          "PacketType");
      }
      /**
       * <code>PACKET_STAT = 0;</code>
       */
      public static final int PACKET_STAT_VALUE = 0;
      /**
       * <code>PACKET_REQ = 1;</code>
       */
      public static final int PACKET_REQ_VALUE = 1;
      /**
       * <code>PACKET_DATA = 2;</code>
       */
      public static final int PACKET_DATA_VALUE = 2;
      /**
       * <code>PACKET_FIN = 3;</code>
       */
      public static final int PACKET_FIN_VALUE = 3;
      /**
       * <code>PACKET_ERR = 4;</code>
       */
      public static final int PACKET_ERR_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static PacketType valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static PacketType forNumber(int value) {
        switch (value) {
          case 0: return PACKET_STAT;
          case 1: return PACKET_REQ;
          case 2: return PACKET_DATA;
          case 3: return PACKET_FIN;
          case 4: return PACKET_ERR;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<PacketType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          PacketType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<PacketType>() {
              public PacketType findValueByNumber(int number) {
                return PacketType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValue(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return fsutil.types.Wire.Packet.getDescriptor().getEnumType(0);
      }

      private static final PacketType[] VALUES = values();

      public static PacketType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private PacketType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:fsutil.types.Packet.PacketType)
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <code>.fsutil.types.Packet.PacketType type = 1;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.fsutil.types.Packet.PacketType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public fsutil.types.Wire.Packet.PacketType getType() {
      fsutil.types.Wire.Packet.PacketType result = fsutil.types.Wire.Packet.PacketType.forNumber(type_);
      return result == null ? fsutil.types.Wire.Packet.PacketType.UNRECOGNIZED : result;
    }

    public static final int STAT_FIELD_NUMBER = 2;
    private fsutil.types.StatOuterClass.Stat stat_;
    /**
     * <code>.fsutil.types.Stat stat = 2;</code>
     * @return Whether the stat field is set.
     */
    @java.lang.Override
    public boolean hasStat() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.fsutil.types.Stat stat = 2;</code>
     * @return The stat.
     */
    @java.lang.Override
    public fsutil.types.StatOuterClass.Stat getStat() {
      return stat_ == null ? fsutil.types.StatOuterClass.Stat.getDefaultInstance() : stat_;
    }
    /**
     * <code>.fsutil.types.Stat stat = 2;</code>
     */
    @java.lang.Override
    public fsutil.types.StatOuterClass.StatOrBuilder getStatOrBuilder() {
      return stat_ == null ? fsutil.types.StatOuterClass.Stat.getDefaultInstance() : stat_;
    }

    public static final int ID_FIELD_NUMBER = 3;
    private int iD_ = 0;
    /**
     * <code>uint32 ID = 3;</code>
     * @return The iD.
     */
    @java.lang.Override
    public int getID() {
      return iD_;
    }

    public static final int DATA_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 4;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != fsutil.types.Wire.Packet.PacketType.PACKET_STAT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getStat());
      }
      if (iD_ != 0) {
        output.writeUInt32(3, iD_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(4, data_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (type_ != fsutil.types.Wire.Packet.PacketType.PACKET_STAT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getStat());
      }
      if (iD_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, iD_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, data_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof fsutil.types.Wire.Packet)) {
        return super.equals(obj);
      }
      fsutil.types.Wire.Packet other = (fsutil.types.Wire.Packet) obj;

      if (type_ != other.type_) return false;
      if (hasStat() != other.hasStat()) return false;
      if (hasStat()) {
        if (!getStat()
            .equals(other.getStat())) return false;
      }
      if (getID()
          != other.getID()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasStat()) {
        hash = (37 * hash) + STAT_FIELD_NUMBER;
        hash = (53 * hash) + getStat().hashCode();
      }
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static fsutil.types.Wire.Packet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsutil.types.Wire.Packet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsutil.types.Wire.Packet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsutil.types.Wire.Packet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsutil.types.Wire.Packet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fsutil.types.Wire.Packet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fsutil.types.Wire.Packet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fsutil.types.Wire.Packet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static fsutil.types.Wire.Packet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static fsutil.types.Wire.Packet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static fsutil.types.Wire.Packet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static fsutil.types.Wire.Packet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(fsutil.types.Wire.Packet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code fsutil.types.Packet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:fsutil.types.Packet)
        fsutil.types.Wire.PacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fsutil.types.Wire.internal_static_fsutil_types_Packet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fsutil.types.Wire.internal_static_fsutil_types_Packet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fsutil.types.Wire.Packet.class, fsutil.types.Wire.Packet.Builder.class);
      }

      // Construct using fsutil.types.Wire.Packet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          internalGetStatFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        stat_ = null;
        if (statBuilder_ != null) {
          statBuilder_.dispose();
          statBuilder_ = null;
        }
        iD_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fsutil.types.Wire.internal_static_fsutil_types_Packet_descriptor;
      }

      @java.lang.Override
      public fsutil.types.Wire.Packet getDefaultInstanceForType() {
        return fsutil.types.Wire.Packet.getDefaultInstance();
      }

      @java.lang.Override
      public fsutil.types.Wire.Packet build() {
        fsutil.types.Wire.Packet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public fsutil.types.Wire.Packet buildPartial() {
        fsutil.types.Wire.Packet result = new fsutil.types.Wire.Packet(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(fsutil.types.Wire.Packet result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.stat_ = statBuilder_ == null
              ? stat_
              : statBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.iD_ = iD_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.data_ = data_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fsutil.types.Wire.Packet) {
          return mergeFrom((fsutil.types.Wire.Packet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fsutil.types.Wire.Packet other) {
        if (other == fsutil.types.Wire.Packet.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasStat()) {
          mergeStat(other.getStat());
        }
        if (other.getID() != 0) {
          setID(other.getID());
        }
        if (!other.getData().isEmpty()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                input.readMessage(
                    internalGetStatFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                iD_ = input.readUInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.fsutil.types.Packet.PacketType type = 1;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.fsutil.types.Packet.PacketType type = 1;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.fsutil.types.Packet.PacketType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public fsutil.types.Wire.Packet.PacketType getType() {
        fsutil.types.Wire.Packet.PacketType result = fsutil.types.Wire.Packet.PacketType.forNumber(type_);
        return result == null ? fsutil.types.Wire.Packet.PacketType.UNRECOGNIZED : result;
      }
      /**
       * <code>.fsutil.types.Packet.PacketType type = 1;</code>
       * @param value The type to set.
       * @throws IllegalArgumentException if UNRECOGNIZED is provided.
       * @return This builder for chaining.
       */
      public Builder setType(fsutil.types.Wire.Packet.PacketType value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.fsutil.types.Packet.PacketType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private fsutil.types.StatOuterClass.Stat stat_;
      private com.google.protobuf.SingleFieldBuilder<
          fsutil.types.StatOuterClass.Stat, fsutil.types.StatOuterClass.Stat.Builder, fsutil.types.StatOuterClass.StatOrBuilder> statBuilder_;
      /**
       * <code>.fsutil.types.Stat stat = 2;</code>
       * @return Whether the stat field is set.
       */
      public boolean hasStat() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.fsutil.types.Stat stat = 2;</code>
       * @return The stat.
       */
      public fsutil.types.StatOuterClass.Stat getStat() {
        if (statBuilder_ == null) {
          return stat_ == null ? fsutil.types.StatOuterClass.Stat.getDefaultInstance() : stat_;
        } else {
          return statBuilder_.getMessage();
        }
      }
      /**
       * <code>.fsutil.types.Stat stat = 2;</code>
       */
      public Builder setStat(fsutil.types.StatOuterClass.Stat value) {
        if (statBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          stat_ = value;
        } else {
          statBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.fsutil.types.Stat stat = 2;</code>
       */
      public Builder setStat(
          fsutil.types.StatOuterClass.Stat.Builder builderForValue) {
        if (statBuilder_ == null) {
          stat_ = builderForValue.build();
        } else {
          statBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.fsutil.types.Stat stat = 2;</code>
       */
      public Builder mergeStat(fsutil.types.StatOuterClass.Stat value) {
        if (statBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            stat_ != null &&
            stat_ != fsutil.types.StatOuterClass.Stat.getDefaultInstance()) {
            getStatBuilder().mergeFrom(value);
          } else {
            stat_ = value;
          }
        } else {
          statBuilder_.mergeFrom(value);
        }
        if (stat_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.fsutil.types.Stat stat = 2;</code>
       */
      public Builder clearStat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stat_ = null;
        if (statBuilder_ != null) {
          statBuilder_.dispose();
          statBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.fsutil.types.Stat stat = 2;</code>
       */
      public fsutil.types.StatOuterClass.Stat.Builder getStatBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return internalGetStatFieldBuilder().getBuilder();
      }
      /**
       * <code>.fsutil.types.Stat stat = 2;</code>
       */
      public fsutil.types.StatOuterClass.StatOrBuilder getStatOrBuilder() {
        if (statBuilder_ != null) {
          return statBuilder_.getMessageOrBuilder();
        } else {
          return stat_ == null ?
              fsutil.types.StatOuterClass.Stat.getDefaultInstance() : stat_;
        }
      }
      /**
       * <code>.fsutil.types.Stat stat = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          fsutil.types.StatOuterClass.Stat, fsutil.types.StatOuterClass.Stat.Builder, fsutil.types.StatOuterClass.StatOrBuilder> 
          internalGetStatFieldBuilder() {
        if (statBuilder_ == null) {
          statBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              fsutil.types.StatOuterClass.Stat, fsutil.types.StatOuterClass.Stat.Builder, fsutil.types.StatOuterClass.StatOrBuilder>(
                  getStat(),
                  getParentForChildren(),
                  isClean());
          stat_ = null;
        }
        return statBuilder_;
      }

      private int iD_ ;
      /**
       * <code>uint32 ID = 3;</code>
       * @return The iD.
       */
      @java.lang.Override
      public int getID() {
        return iD_;
      }
      /**
       * <code>uint32 ID = 3;</code>
       * @param value The iD to set.
       * @return This builder for chaining.
       */
      public Builder setID(int value) {

        iD_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 ID = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        iD_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 4;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 4;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000008);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:fsutil.types.Packet)
    }

    // @@protoc_insertion_point(class_scope:fsutil.types.Packet)
    private static final fsutil.types.Wire.Packet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new fsutil.types.Wire.Packet();
    }

    public static fsutil.types.Wire.Packet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Packet>
        PARSER = new com.google.protobuf.AbstractParser<Packet>() {
      @java.lang.Override
      public Packet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Packet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Packet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public fsutil.types.Wire.Packet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_fsutil_types_Packet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_fsutil_types_Packet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027fsutil/types/wire.proto\022\014fsutil.types\032" +
      "\031vtproto/vtproto/ext.proto\032\027fsutil/types" +
      "/stat.proto\"\331\001\n\006Packet\022-\n\004type\030\001 \001(\0162\037.f" +
      "sutil.types.Packet.PacketType\022 \n\004stat\030\002 " +
      "\001(\0132\022.fsutil.types.Stat\022\n\n\002ID\030\003 \001(\r\022\014\n\004d" +
      "ata\030\004 \001(\014\"^\n\nPacketType\022\017\n\013PACKET_STAT\020\000" +
      "\022\016\n\nPACKET_REQ\020\001\022\017\n\013PACKET_DATA\020\002\022\016\n\nPAC" +
      "KET_FIN\020\003\022\016\n\nPACKET_ERR\020\004:\004\250\246\037\001B$Z\"githu" +
      "b.com/tonistiigi/fsutil/typesb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.VTProto.getDescriptor(),
          fsutil.types.StatOuterClass.getDescriptor(),
        });
    internal_static_fsutil_types_Packet_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_fsutil_types_Packet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_fsutil_types_Packet_descriptor,
        new java.lang.String[] { "Type", "Stat", "ID", "Data", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.VTProto.getDescriptor();
    fsutil.types.StatOuterClass.getDescriptor();
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.protobuf.VTProto.mempool);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
