// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: moby/buildkit/v1/secrets.proto
// Protobuf Java Version: 4.35.1

package moby.buildkit.secrets.v1;

@com.google.protobuf.Generated
public final class SecretsOuterClass extends com.google.protobuf.GeneratedFile {
  private SecretsOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "SecretsOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetSecretRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:moby.buildkit.secrets.v1.GetSecretRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string ID = 1;</code>
     * @return The iD.
     */
    java.lang.String getID();
    /**
     * <code>string ID = 1;</code>
     * @return The bytes for iD.
     */
    com.google.protobuf.ByteString
        getIDBytes();

    /**
     * <code>map&lt;string, string&gt; annotations = 2;</code>
     */
    int getAnnotationsCount();
    /**
     * <code>map&lt;string, string&gt; annotations = 2;</code>
     */
    boolean containsAnnotations(
        java.lang.String key);
    /**
     * Use {@link #getAnnotationsMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getAnnotations();
    /**
     * <code>map&lt;string, string&gt; annotations = 2;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getAnnotationsMap();
    /**
     * <code>map&lt;string, string&gt; annotations = 2;</code>
     */
    /* nullable */
java.lang.String getAnnotationsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; annotations = 2;</code>
     */
    java.lang.String getAnnotationsOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code moby.buildkit.secrets.v1.GetSecretRequest}
   */
  public static final class GetSecretRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:moby.buildkit.secrets.v1.GetSecretRequest)
      GetSecretRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "GetSecretRequest");
    }
    // Use GetSecretRequest.newBuilder() to construct.
    private GetSecretRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetSecretRequest() {
      iD_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretRequest_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 2:
          return internalGetAnnotations();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest.class, moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object iD_ = "";
    /**
     * <code>string ID = 1;</code>
     * @return The iD.
     */
    @java.lang.Override
    public java.lang.String getID() {
      java.lang.Object ref = iD_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iD_ = s;
        return s;
      }
    }
    /**
     * <code>string ID = 1;</code>
     * @return The bytes for iD.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIDBytes() {
      java.lang.Object ref = iD_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iD_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ANNOTATIONS_FIELD_NUMBER = 2;
    private static final class AnnotationsDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretRequest_AnnotationsEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> annotations_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetAnnotations() {
      if (annotations_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            AnnotationsDefaultEntryHolder.defaultEntry);
      }
      return annotations_;
    }
    public int getAnnotationsCount() {
      return internalGetAnnotations().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 2;</code>
     */
    @java.lang.Override
    public boolean containsAnnotations(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetAnnotations().getMap().containsKey(key);
    }
    /**
     * Use {@link #getAnnotationsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getAnnotations() {
      return getAnnotationsMap();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 2;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getAnnotationsMap() {
      return internalGetAnnotations().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 2;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getAnnotationsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAnnotations().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; annotations = 2;</code>
     */
    @java.lang.Override
    public java.lang.String getAnnotationsOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetAnnotations().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(iD_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, iD_);
      }
      com.google.protobuf.GeneratedMessage
        .serializeStringMapTo(
          output,
          internalGetAnnotations(),
          AnnotationsDefaultEntryHolder.defaultEntry,
          2);
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(iD_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, iD_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetAnnotations().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        annotations__ = AnnotationsDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .buildPartial();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, annotations__);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest)) {
        return super.equals(obj);
      }
      moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest other = (moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest) obj;

      if (!getID()
          .equals(other.getID())) return false;
      if (!internalGetAnnotations().equals(
          other.internalGetAnnotations())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getID().hashCode();
      if (!internalGetAnnotations().getMap().isEmpty()) {
        hash = (37 * hash) + ANNOTATIONS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetAnnotations().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code moby.buildkit.secrets.v1.GetSecretRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:moby.buildkit.secrets.v1.GetSecretRequest)
        moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetAnnotations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
          int number) {
        switch (number) {
          case 2:
            return internalGetMutableAnnotations();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest.class, moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest.Builder.class);
      }

      // Construct using moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        iD_ = "";
        internalGetMutableAnnotations().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretRequest_descriptor;
      }

      @java.lang.Override
      public moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest getDefaultInstanceForType() {
        return moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest.getDefaultInstance();
      }

      @java.lang.Override
      public moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest build() {
        moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest buildPartial() {
        moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest result = new moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.iD_ = iD_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.annotations_ = internalGetAnnotations();
          result.annotations_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest) {
          return mergeFrom((moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest other) {
        if (other == moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest.getDefaultInstance()) return this;
        if (!other.getID().isEmpty()) {
          iD_ = other.iD_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        internalGetMutableAnnotations().mergeFrom(
            other.internalGetAnnotations());
        bitField0_ |= 0x00000002;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                iD_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                annotations__ = input.readMessage(
                    AnnotationsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableAnnotations().getMutableMap().put(
                    annotations__.getKey(), annotations__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object iD_ = "";
      /**
       * <code>string ID = 1;</code>
       * @return The iD.
       */
      public java.lang.String getID() {
        java.lang.Object ref = iD_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iD_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ID = 1;</code>
       * @return The bytes for iD.
       */
      public com.google.protobuf.ByteString
          getIDBytes() {
        java.lang.Object ref = iD_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iD_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ID = 1;</code>
       * @param value The iD to set.
       * @return This builder for chaining.
       */
      public Builder setID(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        iD_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string ID = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearID() {
        iD_ = getDefaultInstance().getID();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string ID = 1;</code>
       * @param value The bytes for iD to set.
       * @return This builder for chaining.
       */
      public Builder setIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        iD_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> annotations_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetAnnotations() {
        if (annotations_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              AnnotationsDefaultEntryHolder.defaultEntry);
        }
        return annotations_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableAnnotations() {
        if (annotations_ == null) {
          annotations_ = com.google.protobuf.MapField.newMapField(
              AnnotationsDefaultEntryHolder.defaultEntry);
        }
        if (!annotations_.isMutable()) {
          annotations_ = annotations_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return annotations_;
      }
      public int getAnnotationsCount() {
        return internalGetAnnotations().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 2;</code>
       */
      @java.lang.Override
      public boolean containsAnnotations(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetAnnotations().getMap().containsKey(key);
      }
      /**
       * Use {@link #getAnnotationsMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getAnnotations() {
        return getAnnotationsMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 2;</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getAnnotationsMap() {
        return internalGetAnnotations().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 2;</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getAnnotationsOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAnnotations().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 2;</code>
       */
      @java.lang.Override
      public java.lang.String getAnnotationsOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetAnnotations().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearAnnotations() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableAnnotations().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 2;</code>
       */
      public Builder removeAnnotations(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableAnnotations().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableAnnotations() {
        bitField0_ |= 0x00000002;
        return internalGetMutableAnnotations().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 2;</code>
       */
      public Builder putAnnotations(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableAnnotations().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; annotations = 2;</code>
       */
      public Builder putAllAnnotations(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableAnnotations().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }

      // @@protoc_insertion_point(builder_scope:moby.buildkit.secrets.v1.GetSecretRequest)
    }

    // @@protoc_insertion_point(class_scope:moby.buildkit.secrets.v1.GetSecretRequest)
    private static final moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest();
    }

    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSecretRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetSecretRequest>() {
      @java.lang.Override
      public GetSecretRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetSecretRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSecretRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetSecretResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:moby.buildkit.secrets.v1.GetSecretResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * Protobuf type {@code moby.buildkit.secrets.v1.GetSecretResponse}
   */
  public static final class GetSecretResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:moby.buildkit.secrets.v1.GetSecretResponse)
      GetSecretResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "GetSecretResponse");
    }
    // Use GetSecretResponse.newBuilder() to construct.
    private GetSecretResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GetSecretResponse() {
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretResponse_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse.class, moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse.Builder.class);
    }

    public static final int DATA_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes data = 1;</code>
     * @return The data.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!data_.isEmpty()) {
        output.writeBytes(1, data_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, data_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse)) {
        return super.equals(obj);
      }
      moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse other = (moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse) obj;

      if (!getData()
          .equals(other.getData())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code moby.buildkit.secrets.v1.GetSecretResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:moby.buildkit.secrets.v1.GetSecretResponse)
        moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse.class, moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse.Builder.class);
      }

      // Construct using moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        data_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return moby.buildkit.secrets.v1.SecretsOuterClass.internal_static_moby_buildkit_secrets_v1_GetSecretResponse_descriptor;
      }

      @java.lang.Override
      public moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse getDefaultInstanceForType() {
        return moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse.getDefaultInstance();
      }

      @java.lang.Override
      public moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse build() {
        moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse buildPartial() {
        moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse result = new moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.data_ = data_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse) {
          return mergeFrom((moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse other) {
        if (other == moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse.getDefaultInstance()) return this;
        if (!other.getData().isEmpty()) {
          setData(other.getData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                data_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes data = 1;</code>
       * @return The data.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>bytes data = 1;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        data_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>bytes data = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000001);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:moby.buildkit.secrets.v1.GetSecretResponse)
    }

    // @@protoc_insertion_point(class_scope:moby.buildkit.secrets.v1.GetSecretResponse)
    private static final moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse();
    }

    public static moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetSecretResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetSecretResponse>() {
      @java.lang.Override
      public GetSecretResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GetSecretResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetSecretResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public moby.buildkit.secrets.v1.SecretsOuterClass.GetSecretResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moby_buildkit_secrets_v1_GetSecretRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_moby_buildkit_secrets_v1_GetSecretRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moby_buildkit_secrets_v1_GetSecretRequest_AnnotationsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_moby_buildkit_secrets_v1_GetSecretRequest_AnnotationsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_moby_buildkit_secrets_v1_GetSecretResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_moby_buildkit_secrets_v1_GetSecretResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036moby/buildkit/v1/secrets.proto\022\030moby.b" +
      "uildkit.secrets.v1\"\244\001\n\020GetSecretRequest\022" +
      "\n\n\002ID\030\001 \001(\t\022P\n\013annotations\030\002 \003(\0132;.moby." +
      "buildkit.secrets.v1.GetSecretRequest.Ann" +
      "otationsEntry\0322\n\020AnnotationsEntry\022\013\n\003key" +
      "\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"!\n\021GetSecretRe" +
      "sponse\022\014\n\004data\030\001 \001(\0142o\n\007Secrets\022d\n\tGetSe" +
      "cret\022*.moby.buildkit.secrets.v1.GetSecre" +
      "tRequest\032+.moby.buildkit.secrets.v1.GetS" +
      "ecretResponseB*Z(github.com/moby/buildki" +
      "t/session/secretsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_moby_buildkit_secrets_v1_GetSecretRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_moby_buildkit_secrets_v1_GetSecretRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_moby_buildkit_secrets_v1_GetSecretRequest_descriptor,
        new java.lang.String[] { "ID", "Annotations", });
    internal_static_moby_buildkit_secrets_v1_GetSecretRequest_AnnotationsEntry_descriptor =
      internal_static_moby_buildkit_secrets_v1_GetSecretRequest_descriptor.getNestedType(0);
    internal_static_moby_buildkit_secrets_v1_GetSecretRequest_AnnotationsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_moby_buildkit_secrets_v1_GetSecretRequest_AnnotationsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_moby_buildkit_secrets_v1_GetSecretResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_moby_buildkit_secrets_v1_GetSecretResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_moby_buildkit_secrets_v1_GetSecretResponse_descriptor,
        new java.lang.String[] { "Data", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
